// The homepage shows a background-removed ("cutout") version of each
// product's primary photo. Cutouts live alongside the studio photo at the
// same path with a .png extension (generated by scripts/cutout_products.py).
// Every other surface (shop grid, product page, cart, admin) keeps using
// the original .jpg — only import this where that specific homepage look
// is wanted.
export function cutoutSrc(jpgPath: string): string {
  return jpgPath.replace(/\.jpg$/i, ".png");
}
