// Product cards across the site (homepage rows, shop grid, wishlist, related
// products) show a background-removed ("cutout") version of the primary photo.
// Cutouts are generated by scripts/cutout_products.py and live alongside the
// studio photo at the same path with a .png extension.
//
// Only the bundled catalog art under /products/ has one. Admin-uploaded images
// land on Vercel Blob — or /uploads in local dev — as a UUID keeping whatever
// extension was uploaded, with no cutout sibling, so rewriting their extension
// would point at a 404. Those keep their original file.
const CUTOUT_ROOT = "/products/";

export function cutoutSrc(src: string): string {
  if (!src.startsWith(CUTOUT_ROOT)) return src;
  return src.replace(/\.jpg$/i, ".png");
}
